/**
 * Behringer DeepMind 12 — Executable parameter schema.
 *
 * Byte-offset → parameter mapping extracted from ABDEep's ParameterRegistry.gen.cpp
 * (auto-generated by scripts/validate_and_generate.ps1 → registry_generator.js).
 *
 * Patch data is 242 bytes after 7-to-8 unpacking.
 * codecType: 0 = value (0-255), 1 = bipolar (-128..127), 2 = enum (0..enumMax).
 */

const LFO_SHAPES = ['Sine', 'Triangle', 'Square', 'Ramp Up', 'Ramp Down', 'S&H', 'S&Glide'];
const PORTA_MODES = ['Normal', 'Fingered', 'Fix-Rate', 'Fix-Fing', 'Exp', 'Exp-Fing', 'Fixed+2', 'Fixed-2', 'Fixed+5', 'Fixed-5', 'Fixed+12', 'Fixed-12', 'Fixed+24', 'Fixed-24'];
const VCF_LFO_SOURCES = ['LFO 1', 'LFO 2'];
const VCF_ENV_POLARITIES = ['Inverted', 'Normal'];
const VCF_POLE_MODES = ['4-Pole (24dB)', '2-Pole (12dB)'];
const ENV_TRIGGER_MODES = ['Key', 'LFO 1', 'LFO 2', 'Loop', 'Seq'];
const NOTE_PRIORITIES = ['Lowest', 'Highest', 'Last'];
const VOICE_MODES = ['Poly', 'Unison 2', 'Unison 3', 'Unison 4', 'Unison 6', 'Unison 12', 'Mono', 'Mono 2', 'Mono 3', 'Mono 4', 'Mono 6', 'Poly 6', 'Poly 8'];
const TRIGGER_MODES = ['Mono', 'Retrig', 'Legato', 'One-shot'];
const PM_SOURCES = ['LFO 1', 'LFO 2', 'Env 1', 'Env 2', 'Env 3', 'LFO 1 (Uni)', 'LFO 2 (Uni)'];
const PWM_SOURCES = ['Manual', 'LFO 1', 'LFO 2', 'Env 1', 'Env 2', 'Env 3'];
const OSC_RANGES = ["16'", "8'", "4'"];
const PM_MODES = ['OSC 1+2', 'OSC 1'];
const ARP_MODES = ['Up', 'Down', 'Up-Down', 'Up-Inv', 'Down-Inv', 'Up-Dn-Inv', 'Up-Alt', 'Down-Alt', 'Random', 'As-Played', 'Chord'];
const ARP_CLOCK_DIVS = ['1/2', '3/8', '1/3', '1/4', '3/16', '1/6', '1/8', '3/32', '1/12', '1/16', '1/24', '1/32', '1/48'];
const ARP_OCTAVES = ['1', '2', '3', '4'];
const SEQ_CLOCKS = ['1/2', '3/8', '1/3', '1/4', '3/16', '1/6', '1/8', '1/12', '1/16', '1/24', '1/32', '1/48', '1/64', '1/96', '1/128', '1/192'];
const SEQ_KEY_LOOPS = ['Loop Off', 'Loop On', 'Unused'];
const FX_ROUTINGS = ['Series', 'Parallel Pairs', 'Series Chain', 'Full Parallel', 'Dual Series Parallel', 'Series Split Mid', 'Parallel Pairs Series', 'Series Chain + Parallel', 'Parallel Front Series', 'Series with Feedback'];
const FX_TYPES = ['Bypass', 'HallReverb', 'Plate Reverb', 'Rich Plate', 'Ambience', 'Gated Reverb', 'Reverse Reverb', 'RackAmp', 'Mood Filter', 'Stereo Phaser', 'Stereo Chorus', 'Stereo Flanger', 'ModDlyRev', 'Delay', '3Tap Delay', '4Tap Delay', 'Rotary Speaker', 'Chorus-D', 'Enhancer', 'Edison', 'AutoPan/Trem', 'T-RayDelay', 'tcDeepVerb', 'flangVerb', 'chorusVerb', 'delayVerb', 'ChamberRev', 'RoomRev', 'VintageRoom', 'Dual Pitch', 'MidasEQ', 'FairComp', 'MBDistortion', 'NoiseGate', 'DecimatorDelay', 'Vintage Pitch', 'RolandBBDChorus', 'SolinaEnsemble', 'RingModulator', 'SpaceEchoRE201', 'AnalogTapeDelay', 'ShimmerDelay', 'GranularDelay', 'PatternFreeze', 'DuckingDelay', 'SpectralDelay', 'FreqShifter', 'HarmonicResonator', 'Combulator', 'Vocoder'];
const FX_MODES = ['Stereo', 'Mono', 'DryPan'];
const VCF_MODELS = ['DM12 OTA', 'Moog Ladder', 'Korg MS-20'];
const VCF_MOOG_TYPES = ['Lowpass', 'Bandpass', 'Highpass'];
const VCF_KORG_TYPES = ['K35 Lowpass', 'K35 Highpass'];

/**
 * codecType: 0 = value (raw/255), 1 = bipolar ((raw-128)/127+1)/2, 2 = enum (raw/enumMax)
 * The kByteMapParams array from ParameterRegistry.gen.cpp maps byte offset → display name.
 */
const RAW_BYTE_MAP = [
  'LFO 1 Rate', 'LFO 1 Delay/Fade', 'LFO 1 Shape', 'LFO 1 Key Sync', 'LFO 1 Arp Sync',
  'LFO 1 Mono Mode', 'LFO 1 Slew Rate', 'LFO 2 Rate', 'LFO 2 Delay/Fade', 'LFO 2 Shape',
  'LFO 2 Key Sync', 'LFO 2 Arp Sync', 'LFO 2 Mono Mode', 'LFO 2 Slew Rate',
  'OSC 1 Range', 'OSC 2 Range', 'OSC 1 PWM Source', 'OSC 2 Tone Mod Source',
  'OSC 1 Pulse Enable', 'OSC 1 Saw Enable', 'OSC Sync Enable', 'OSC 1 Pitch Mod Depth',
  'OSC 1 Pitch Mod Select', 'OSC 1 AT > Pitch Mod', 'OSC 1 MW > Pitch Mod', 'OSC 1 PWM Depth',
  'OSC 2 Level', 'OSC 2 Pitch', 'OSC 2 Tone Mod Depth', 'OSC 2 Pitch Mod Depth',
  'OSC 2 AT > Pitch Mod', 'OSC 2 MW > Pitch Mod', 'OSC 2 Pitch Mod Select', 'Noise Level',
  'Portamento Time', 'Portamento Mode', 'Pitch Bend Up', 'Pitch Bend Down',
  'OSC 1 PM Mode', 'VCF Cutoff', 'HPF Cutoff', 'VCF Resonance', 'VCF Env Depth',
  'VCF Env Vel Sens', 'VCF Pitch Bend Depth', 'VCF LFO Depth', 'VCF LFO Select',
  'VCF AT > LFO Depth', 'VCF MW > LFO Depth', 'VCF Key Tracking', 'VCF Env Polarity',
  'VCF 2 Pole Mode', 'HPF Boost Enable',
  'Env1 Attack', 'Env1 Decay', 'Env1 Sustain', 'Env1 Release', 'Env1 Trigger Mode',
  'Env1 Attack Curve', 'Env1 Decay Curve', 'Env1 Sustain Curve', 'Env1 Release Curve',
  'Env2 Attack', 'Env2 Decay', 'Env2 Sustain', 'Env2 Release', 'Env2 Trigger Mode',
  'Env2 Attack Curve', 'Env2 Decay Curve', 'Env2 Sustain Curve', 'Env2 Release Curve',
  'Env3 Attack', 'Env3 Decay', 'Env3 Sustain', 'Env3 Release', 'Env3 Trigger Mode',
  'Env3 Attack Curve', 'Env3 Decay Curve', 'Env3 Sustain Curve', 'Env3 Release Curve',
  'VCA Level', 'VCA Env Depth', 'VCA Vel Sens', 'VCA Pan Spread',
  'Note Priority', 'Voice Mode', 'Trigger Mode', 'Unison Detune', 'Voice Drift',
  'Parameter Drift', 'Drift Rate', 'OSC Porta Balance', 'OSC Key Down Reset',
  'Mod Matrix Slot1 Source', 'Mod Matrix Slot1 Dest', 'Mod Matrix Slot1 Depth',
  'Mod Matrix Slot2 Source', 'Mod Matrix Slot2 Dest', 'Mod Matrix Slot2 Depth',
  'Mod Matrix Slot3 Source', 'Mod Matrix Slot3 Dest', 'Mod Matrix Slot3 Depth',
  'Mod Matrix Slot4 Source', 'Mod Matrix Slot4 Dest', 'Mod Matrix Slot4 Depth',
  'Mod5 Source / Chord Enable', 'Mod5 Dest / Poly Chord', 'Mod5 Depth / Chord Key',
  'Mod6 Source / Chord Type', 'Mod6 Dest / Arp Enable', 'Mod6 Depth / Arp Hold',
  'Mod7 Source / Arp KeySync', 'Mod7 Dest / Arp Gate', 'Mod7 Depth / Arp Mode',
  'Mod8 Source (unused)', 'Mod8 Dest / Arp GateTime', 'Mod8 Depth / Arp Swing',
  'Seq Enable', 'Seq Clock Divider', 'Seq Length', 'Seq Swing', 'Seq Key Loop', 'Seq Slew Rate',
  'Seq Step 1', 'Seq Step 2', 'Seq Step 3', 'Seq Step 4', 'Seq Step 5', 'Seq Step 6',
  'Seq Step 7', 'Seq Step 8', 'Seq Step 9', 'Seq Step 10', 'Seq Step 11', 'Seq Step 12',
  'Seq Step 13', 'Seq Step 14', 'Seq Step 15', 'Seq Step 16', 'Seq Step 17', 'Seq Step 18',
  'Seq Step 19', 'Seq Step 20', 'Seq Step 21', 'Seq Step 22', 'Seq Step 23', 'Seq Step 24',
  'Seq Step 25', 'Seq Step 26', 'Seq Step 27', 'Seq Step 28', 'Seq Step 29', 'Seq Step 30',
  'Seq Step 31', 'Seq Step 32',
  'Arp On/Off', 'Arp Mode', 'Arp Rate', 'Arp Clock Divider', 'Arp Key Sync',
  'Arp Gate Time', 'Arp Hold', 'Arp Pattern', 'Arp Swing', 'Arp Octaves',
  'FX Routing', 'FX1 Type', 'FX1 Param 1', 'FX1 Param 2', 'FX1 Param 3', 'FX1 Param 4',
  'FX1 Param 5', 'FX1 Param 6', 'FX1 Param 7', 'FX1 Param 8', 'FX1 Param 9', 'FX1 Param 10',
  'FX1 Param 11', 'FX1 Param 12',
  'FX2 Type', 'FX2 Param 1', 'FX2 Param 2', 'FX2 Param 3', 'FX2 Param 4', 'FX2 Param 5',
  'FX2 Param 6', 'FX2 Param 7', 'FX2 Param 8', 'FX2 Param 9', 'FX2 Param 10', 'FX2 Param 11',
  'FX2 Param 12',
  'FX3 Type', 'FX3 Param 1', 'FX3 Param 2', 'FX3 Param 3', 'FX3 Param 4', 'FX3 Param 5',
  'FX3 Param 6', 'FX3 Param 7', 'FX3 Param 8', 'FX3 Param 9', 'FX3 Param 10', 'FX3 Param 11',
  'FX3 Param 12',
  'FX4 Type', 'FX4 Param 1', 'FX4 Param 2', 'FX4 Param 3', 'FX4 Param 4', 'FX4 Param 5',
  'FX4 Param 6', 'FX4 Param 7', 'FX4 Param 8', 'FX4 Param 9', 'FX4 Param 10', 'FX4 Param 11',
  'FX4 Param 12',
  'FX1 Output Gain', 'FX2 Output Gain', 'FX3 Output Gain', 'FX4 Output Gain', 'FX Mode',
  'Program Name char[0]', 'Program Name char[1]', 'Program Name char[2]', 'Program Name char[3]',
  'Program Name char[4]', 'Program Name char[5]', 'Program Name char[6]', 'Program Name char[7]',
  'Program Name char[8]', 'Program Name char[9]', 'Program Name char[10]', 'Program Name char[11]',
  'Program Name char[12]', 'Program Name char[13]', 'Program Name char[14]', 'Program Name char[15]',
  '(name field tail)', '(name field tail)', '(name field tail)'
];

/**
 * Parameter definitions with codec type, enum options, and CC mappings.
 * Derived from ParametersSpec_*.cpp + ParameterRegistry.gen.cpp in ABDEep.
 */
export const DEEPMIND_PARAMETER_SCHEMA = [
  // LFO 1
  { id: 'lfo1-rate', name: 'LFO1 Rate', section: 'LFO1', offset: 0, kind: 'value', cc: 16, description: 'LFO 1 rate' },
  { id: 'lfo1-delay', name: 'LFO1 Delay', section: 'LFO1', offset: 1, kind: 'value', cc: 17, description: 'LFO 1 delay/fade time' },
  { id: 'lfo1-shape', name: 'LFO1 Shape', section: 'LFO1', offset: 2, kind: 'enum', enumMax: 6, options: LFO_SHAPES, description: 'LFO 1 waveform shape' },
  { id: 'lfo1-key-sync', name: 'LFO1 Key Sync', section: 'LFO1', offset: 3, kind: 'enum', enumMax: 1, options: ['Off', 'On'], description: 'LFO 1 key press sync' },
  { id: 'lfo1-arp-sync', name: 'LFO1 Arp Sync', section: 'LFO1', offset: 4, kind: 'enum', enumMax: 1, options: ['Off', 'On'], description: 'LFO 1 arpeggiator sync' },
  { id: 'lfo1-mono-mode', name: 'LFO1 Mono Mode', section: 'LFO1', offset: 5, kind: 'value', description: 'LFO 1 mono mode amount' },
  { id: 'lfo1-slew', name: 'LFO1 Slew', section: 'LFO1', offset: 6, kind: 'value', description: 'LFO 1 slew rate' },
  // LFO 2
  { id: 'lfo2-rate', name: 'LFO2 Rate', section: 'LFO2', offset: 7, kind: 'value', description: 'LFO 2 rate' },
  { id: 'lfo2-delay', name: 'LFO2 Delay', section: 'LFO2', offset: 8, kind: 'value', description: 'LFO 2 delay/fade time' },
  { id: 'lfo2-shape', name: 'LFO2 Shape', section: 'LFO2', offset: 9, kind: 'enum', enumMax: 6, options: LFO_SHAPES, description: 'LFO 2 waveform shape' },
  { id: 'lfo2-key-sync', name: 'LFO2 Key Sync', section: 'LFO2', offset: 10, kind: 'enum', enumMax: 1, options: ['Off', 'On'], description: 'LFO 2 key press sync' },
  { id: 'lfo2-arp-sync', name: 'LFO2 Arp Sync', section: 'LFO2', offset: 11, kind: 'enum', enumMax: 1, options: ['Off', 'On'], description: 'LFO 2 arpeggiator sync' },
  { id: 'lfo2-mono-mode', name: 'LFO2 Mono Mode', section: 'LFO2', offset: 12, kind: 'value', description: 'LFO 2 mono mode amount' },
  { id: 'lfo2-slew', name: 'LFO2 Slew', section: 'LFO2', offset: 13, kind: 'value', description: 'LFO 2 slew rate' },
  // OSC 1
  { id: 'osc1-range', name: 'OSC1 Range', section: 'OSC1', offset: 14, kind: 'enum', enumMax: 2, options: OSC_RANGES, description: 'Oscillator 1 octave range' },
  { id: 'osc2-range', name: 'OSC2 Range', section: 'OSC2', offset: 15, kind: 'enum', enumMax: 2, options: OSC_RANGES, description: 'Oscillator 2 octave range' },
  { id: 'osc1-pwm-source', name: 'OSC1 PWM Source', section: 'OSC1', offset: 16, kind: 'enum', enumMax: 5, options: PWM_SOURCES, description: 'Oscillator 1 PWM modulation source' },
  { id: 'osc2-tpm-source', name: 'OSC2 Tone Mod Source', section: 'OSC2', offset: 17, kind: 'enum', enumMax: 5, options: PWM_SOURCES, description: 'Oscillator 2 tone modulation source' },
  { id: 'osc1-square-enable', name: 'OSC1 Pulse Enable', section: 'OSC1', offset: 18, kind: 'enum', enumMax: 1, options: ['Off', 'On'], description: 'Oscillator 1 pulse/square waveform enable' },
  { id: 'osc1-saw-enable', name: 'OSC1 Saw Enable', section: 'OSC1', offset: 19, kind: 'enum', enumMax: 1, options: ['Off', 'On'], description: 'Oscillator 1 sawtooth waveform enable' },
  { id: 'osc-sync-enable', name: 'OSC Sync Enable', section: 'OSC', offset: 20, kind: 'enum', enumMax: 1, options: ['Off', 'On'], description: 'Oscillator hard sync enable' },
  { id: 'osc1-pitch-mod', name: 'OSC1 Pitch Mod Depth', section: 'OSC1', offset: 21, kind: 'value', cc: 20, description: 'Oscillator 1 pitch modulation depth' },
  { id: 'osc1-pm-source', name: 'OSC1 Pitch Mod Select', section: 'OSC1', offset: 22, kind: 'enum', enumMax: 6, options: PM_SOURCES, description: 'Oscillator 1 pitch modulation source' },
  { id: 'osc1-lfo-aftertouch', name: 'OSC1 AT > Pitch Mod', section: 'OSC1', offset: 23, kind: 'value', description: 'Oscillator 1 aftertouch to pitch modulation' },
  { id: 'osc1-lfo-modwheel', name: 'OSC1 MW > Pitch Mod', section: 'OSC1', offset: 24, kind: 'value', description: 'Oscillator 1 mod wheel to pitch modulation' },
  { id: 'osc1-pwm-amount', name: 'OSC1 PWM Depth', section: 'OSC1', offset: 25, kind: 'value', cc: 21, description: 'Oscillator 1 PWM depth' },
  // OSC 2
  { id: 'osc2-level', name: 'OSC2 Level', section: 'OSC2', offset: 26, kind: 'value', cc: 26, description: 'Oscillator 2 output level' },
  { id: 'osc2-pitch', name: 'OSC2 Pitch', section: 'OSC2', offset: 27, kind: 'bipolar', cc: 25, description: 'Oscillator 2 fine pitch (-12 to +12 semitones)' },
  { id: 'osc2-tone-mod', name: 'OSC2 Tone Mod Depth', section: 'OSC2', offset: 28, kind: 'value', cc: 24, description: 'Oscillator 2 tone modulation depth' },
  { id: 'osc2-pitch-mod', name: 'OSC2 Pitch Mod Depth', section: 'OSC2', offset: 29, kind: 'bipolar', cc: 23, description: 'Oscillator 2 pitch modulation depth' },
  { id: 'osc2-aftertouch-pitch', name: 'OSC2 AT > Pitch Mod', section: 'OSC2', offset: 30, kind: 'value', description: 'Oscillator 2 aftertouch to pitch modulation' },
  { id: 'osc2-modwheel-pitch', name: 'OSC2 MW > Pitch Mod', section: 'OSC2', offset: 31, kind: 'value', description: 'Oscillator 2 mod wheel to pitch modulation' },
  { id: 'osc2-pitch-mod-select', name: 'OSC2 Pitch Mod Select', section: 'OSC2', offset: 32, kind: 'enum', enumMax: 6, options: PM_SOURCES, description: 'Oscillator 2 pitch modulation source' },
  { id: 'noise-level', name: 'Noise Level', section: 'Noise', offset: 33, kind: 'value', cc: 27, description: 'White noise generator level' },
  // Performance
  { id: 'global-portamento', name: 'Portamento Time', section: 'Porta', offset: 34, kind: 'value', cc: 5, description: 'Global portamento/glide time' },
  { id: 'porta-mode', name: 'Portamento Mode', section: 'Porta', offset: 35, kind: 'enum', enumMax: 9, options: PORTA_MODES, description: 'Portamento mode' },
  { id: 'pitch-bend-up', name: 'Pitch Bend Up', section: 'Pitch', offset: 36, kind: 'value', description: 'Pitch bend range upward (0-24 semitones)' },
  { id: 'pitch-bend-down', name: 'Pitch Bend Down', section: 'Pitch', offset: 37, kind: 'value', description: 'Pitch bend range downward (0-24 semitones)' },
  { id: 'osc1-pm-mode', name: 'OSC1 PM Mode', section: 'Pitch', offset: 38, kind: 'enum', enumMax: 1, options: PM_MODES, description: 'Oscillator 1 pitch mod mode' },
  // VCF
  { id: 'vcf-cutoff', name: 'VCF Cutoff', section: 'VCF', offset: 39, kind: 'value', cc: 29, description: 'Voltage controlled filter cutoff frequency' },
  { id: 'hpf-cutoff', name: 'HPF Cutoff', section: 'HPF', offset: 40, kind: 'value', cc: 35, description: 'High pass filter cutoff frequency' },
  { id: 'vcf-resonance', name: 'VCF Resonance', section: 'VCF', offset: 41, kind: 'value', cc: 30, description: 'VCF resonance amount' },
  { id: 'vcf-env-depth', name: 'VCF Env Depth', section: 'VCF', offset: 42, kind: 'bipolar', cc: 31, description: 'VCF envelope modulation depth (bipolar)' },
  { id: 'vcf-env-vel', name: 'VCF Env Vel Sens', section: 'VCF', offset: 43, kind: 'value', description: 'VCF envelope velocity sensitivity' },
  { id: 'vcf-pitch-bend', name: 'VCF Pitch Bend Depth', section: 'VCF', offset: 44, kind: 'value', description: 'VCF pitch bend modulation depth' },
  { id: 'vcf-lfo-depth', name: 'VCF LFO Depth', section: 'VCF', offset: 45, kind: 'value', cc: 33, description: 'VCF LFO modulation depth' },
  { id: 'vcf-lfo-select', name: 'VCF LFO Select', section: 'VCF', offset: 46, kind: 'enum', enumMax: 1, options: VCF_LFO_SOURCES, description: 'VCF LFO source select' },
  { id: 'vcf-aftertouch-lfo', name: 'VCF AT > LFO Depth', section: 'VCF', offset: 47, kind: 'value', description: 'VCF aftertouch to LFO depth' },
  { id: 'vcf-modwheel-lfo', name: 'VCF MW > LFO Depth', section: 'VCF', offset: 48, kind: 'value', description: 'VCF mod wheel to LFO depth' },
  { id: 'vcf-key-tracking', name: 'VCF Key Tracking', section: 'VCF', offset: 49, kind: 'value', cc: 34, description: 'VCF keyboard tracking amount' },
  { id: 'vcf-env-polarity', name: 'VCF Env Polarity', section: 'VCF', offset: 50, kind: 'enum', enumMax: 1, options: VCF_ENV_POLARITIES, description: 'VCF envelope polarity' },
  { id: 'vcf-pole-mode', name: 'VCF Pole Mode', section: 'VCF', offset: 51, kind: 'enum', enumMax: 1, options: VCF_POLE_MODES, description: 'VCF filter slope mode' },
  { id: 'hpf-boost-enable', name: 'HPF Boost Enable', section: 'HPF', offset: 52, kind: 'enum', enumMax: 1, options: ['Off', 'On'], description: 'HPF bass boost enable' },
  // Envelope 1 (VCA)
  { id: 'env1-attack', name: 'Env1 Attack', section: 'ENV1', offset: 53, kind: 'value', cc: 37, description: 'Envelope 1 (VCA) attack time' },
  { id: 'env1-decay', name: 'Env1 Decay', section: 'ENV1', offset: 54, kind: 'value', cc: 39, description: 'Envelope 1 (VCA) decay time' },
  { id: 'env1-sustain', name: 'Env1 Sustain', section: 'ENV1', offset: 55, kind: 'value', cc: 40, description: 'Envelope 1 (VCA) sustain level' },
  { id: 'env1-release', name: 'Env1 Release', section: 'ENV1', offset: 56, kind: 'value', cc: 41, description: 'Envelope 1 (VCA) release time' },
  { id: 'env1-trigger-mode', name: 'Env1 Trigger Mode', section: 'ENV1', offset: 57, kind: 'enum', enumMax: 4, options: ENV_TRIGGER_MODES, description: 'Envelope 1 trigger mode' },
  { id: 'env1-attack-curve', name: 'Env1 Attack Curve', section: 'ENV1', offset: 58, kind: 'value', description: 'Envelope 1 attack curve shape' },
  { id: 'env1-decay-curve', name: 'Env1 Decay Curve', section: 'ENV1', offset: 59, kind: 'value', description: 'Envelope 1 decay curve shape' },
  { id: 'env1-sustain-curve', name: 'Env1 Sustain Curve', section: 'ENV1', offset: 60, kind: 'value', description: 'Envelope 1 sustain curve shape' },
  { id: 'env1-release-curve', name: 'Env1 Release Curve', section: 'ENV1', offset: 61, kind: 'value', description: 'Envelope 1 release curve shape' },
  // Envelope 2 (VCF)
  { id: 'env2-attack', name: 'Env2 Attack', section: 'ENV2', offset: 62, kind: 'value', cc: 42, description: 'Envelope 2 (VCF) attack time' },
  { id: 'env2-decay', name: 'Env2 Decay', section: 'ENV2', offset: 63, kind: 'value', cc: 43, description: 'Envelope 2 (VCF) decay time' },
  { id: 'env2-sustain', name: 'Env2 Sustain', section: 'ENV2', offset: 64, kind: 'value', cc: 44, description: 'Envelope 2 (VCF) sustain level' },
  { id: 'env2-release', name: 'Env2 Release', section: 'ENV2', offset: 65, kind: 'value', cc: 45, description: 'Envelope 2 (VCF) release time' },
  { id: 'env2-trigger-mode', name: 'Env2 Trigger Mode', section: 'ENV2', offset: 66, kind: 'enum', enumMax: 4, options: ENV_TRIGGER_MODES, description: 'Envelope 2 trigger mode' },
  { id: 'env2-attack-curve', name: 'Env2 Attack Curve', section: 'ENV2', offset: 67, kind: 'value', description: 'Envelope 2 attack curve shape' },
  { id: 'env2-decay-curve', name: 'Env2 Decay Curve', section: 'ENV2', offset: 68, kind: 'value', description: 'Envelope 2 decay curve shape' },
  { id: 'env2-sustain-curve', name: 'Env2 Sustain Curve', section: 'ENV2', offset: 69, kind: 'value', description: 'Envelope 2 sustain curve shape' },
  { id: 'env2-release-curve', name: 'Env2 Release Curve', section: 'ENV2', offset: 70, kind: 'value', description: 'Envelope 2 release curve shape' },
  // Envelope 3 (Mod)
  { id: 'env3-attack', name: 'Env3 Attack', section: 'ENV3', offset: 71, kind: 'value', cc: 46, description: 'Envelope 3 (Mod) attack time' },
  { id: 'env3-decay', name: 'Env3 Decay', section: 'ENV3', offset: 72, kind: 'value', cc: 47, description: 'Envelope 3 (Mod) decay time' },
  { id: 'env3-sustain', name: 'Env3 Sustain', section: 'ENV3', offset: 73, kind: 'value', cc: 48, description: 'Envelope 3 (Mod) sustain level' },
  { id: 'env3-release', name: 'Env3 Release', section: 'ENV3', offset: 74, kind: 'value', cc: 49, description: 'Envelope 3 (Mod) release time' },
  { id: 'env3-trigger-mode', name: 'Env3 Trigger Mode', section: 'ENV3', offset: 75, kind: 'enum', enumMax: 4, options: ENV_TRIGGER_MODES, description: 'Envelope 3 trigger mode' },
  { id: 'env3-attack-curve', name: 'Env3 Attack Curve', section: 'ENV3', offset: 76, kind: 'value', description: 'Envelope 3 attack curve shape' },
  { id: 'env3-decay-curve', name: 'Env3 Decay Curve', section: 'ENV3', offset: 77, kind: 'value', description: 'Envelope 3 decay curve shape' },
  { id: 'env3-sustain-curve', name: 'Env3 Sustain Curve', section: 'ENV3', offset: 78, kind: 'value', description: 'Envelope 3 sustain curve shape' },
  { id: 'env3-release-curve', name: 'Env3 Release Curve', section: 'ENV3', offset: 79, kind: 'value', description: 'Envelope 3 release curve shape' },
  // VCA
  { id: 'vca-level', name: 'VCA Level', section: 'VCA', offset: 80, kind: 'value', cc: 36, description: 'Voltage controlled amplifier level' },
  { id: 'vca-env-depth', name: 'VCA Env Depth', section: 'VCA', offset: 81, kind: 'value', description: 'VCA envelope modulation depth' },
  { id: 'vca-vel-sens', name: 'VCA Vel Sens', section: 'VCA', offset: 82, kind: 'value', description: 'VCA velocity sensitivity' },
  { id: 'vca-pan-spread', name: 'VCA Pan Spread', section: 'VCA', offset: 83, kind: 'bipolar', description: 'VCA stereo pan spread (bipolar)' },
  // Voice
  { id: 'note-priority', name: 'Note Priority', section: 'Voice', offset: 84, kind: 'enum', enumMax: 2, options: NOTE_PRIORITIES, description: 'Note priority mode' },
  { id: 'voice-mode', name: 'Voice Mode', section: 'Voice', offset: 85, kind: 'enum', enumMax: 12, options: VOICE_MODES, description: 'Voice allocation mode' },
  { id: 'trigger-mode', name: 'Trigger Mode', section: 'Voice', offset: 86, kind: 'enum', enumMax: 3, options: TRIGGER_MODES, description: 'Note trigger mode' },
  { id: 'unison-detune', name: 'Unison Detune', section: 'Voice', offset: 87, kind: 'value', cc: 28, description: 'Unison voice detune amount' },
  { id: 'voice-drift', name: 'Voice Drift', section: 'Voice', offset: 88, kind: 'value', description: 'Voice drift amount' },
  { id: 'param-drift', name: 'Parameter Drift', section: 'Voice', offset: 89, kind: 'value', description: 'Parameter drift amount' },
  { id: 'drift-rate', name: 'Drift Rate', section: 'Voice', offset: 90, kind: 'value', description: 'Drift rate speed' },
  { id: 'porta-osc-bal', name: 'OSC Porta Balance', section: 'Voice', offset: 91, kind: 'bipolar', description: 'Portamento oscillator balance (bipolar)' },
  { id: 'osc-key-reset', name: 'OSC Key Down Reset', section: 'Voice', offset: 92, kind: 'enum', enumMax: 1, options: ['Off', 'On'], description: 'Oscillator key down reset' },
  // Modulation Matrix (8 slots × 3)
  ...Array.from({ length: 8 }, (_, i) => [
    { id: `mod-slot${i + 1}-src`, name: `Mod Slot ${i + 1} Source`, section: 'ModMatrix', offset: 93 + i * 3, kind: 'value', description: `Modulation matrix slot ${i + 1} source` },
    { id: `mod-slot${i + 1}-dest`, name: `Mod Slot ${i + 1} Dest`, section: 'ModMatrix', offset: 94 + i * 3, kind: 'value', description: `Modulation matrix slot ${i + 1} destination` },
    { id: `mod-slot${i + 1}-depth`, name: `Mod Slot ${i + 1} Depth`, section: 'ModMatrix', offset: 95 + i * 3, kind: 'bipolar', description: `Modulation matrix slot ${i + 1} depth (bipolar)` }
  ]).flat(),
  // Sequencer
  { id: 'seq-enable', name: 'Seq Enable', section: 'Seq', offset: 117, kind: 'enum', enumMax: 1, options: ['Off', 'On'], description: 'Control sequencer enable' },
  { id: 'seq-clock', name: 'Seq Clock Divider', section: 'Seq', offset: 118, kind: 'enum', enumMax: 15, options: SEQ_CLOCKS, description: 'Sequencer clock divider' },
  { id: 'seq-length', name: 'Seq Length', section: 'Seq', offset: 119, kind: 'value', description: 'Sequencer length (1-32 steps)' },
  { id: 'seq-swing', name: 'Seq Swing', section: 'Seq', offset: 120, kind: 'value', description: 'Sequencer swing amount' },
  { id: 'seq-key-loop', name: 'Seq Key Loop', section: 'Seq', offset: 121, kind: 'enum', enumMax: 2, options: SEQ_KEY_LOOPS, description: 'Sequencer key loop mode' },
  { id: 'seq-slew-rate', name: 'Seq Slew Rate', section: 'Seq', offset: 122, kind: 'value', description: 'Sequencer slew rate' },
  // Seq Steps 1-32
  ...Array.from({ length: 32 }, (_, i) => ({
    id: `seq-step-${i + 1}`, name: `Seq Step ${i + 1}`, section: 'SeqSteps', offset: 123 + i, kind: 'bipolar', description: `Sequencer step ${i + 1} value (bipolar)`
  })),
  // Arpeggiator
  { id: 'arp-enable', name: 'Arp On/Off', section: 'Arp', offset: 155, kind: 'enum', enumMax: 1, options: ['Off', 'On'], description: 'Arpeggiator enable' },
  { id: 'arp-mode', name: 'Arp Mode', section: 'Arp', offset: 156, kind: 'enum', enumMax: 10, options: ARP_MODES, description: 'Arpeggiator mode' },
  { id: 'arp-rate', name: 'Arp Rate', section: 'Arp', offset: 157, kind: 'value', cc: 12, description: 'Arpeggiator rate (BPM)' },
  { id: 'arp-clock-divider', name: 'Arp Clock Divider', section: 'Arp', offset: 158, kind: 'enum', enumMax: 12, options: ARP_CLOCK_DIVS, description: 'Arpeggiator clock divider' },
  { id: 'arp-key-sync', name: 'Arp Key Sync', section: 'Arp', offset: 159, kind: 'enum', enumMax: 1, options: ['Off', 'On'], description: 'Arpeggiator key sync' },
  { id: 'arp-gate-time', name: 'Arp Gate Time', section: 'Arp', offset: 160, kind: 'value', cc: 13, description: 'Arpeggiator gate time' },
  { id: 'arp-hold', name: 'Arp Hold', section: 'Arp', offset: 161, kind: 'enum', enumMax: 1, options: ['Off', 'On'], description: 'Arpeggiator hold mode' },
  { id: 'arp-pattern', name: 'Arp Pattern', section: 'Arp', offset: 162, kind: 'value', description: 'Arpeggiator pattern preset' },
  { id: 'arp-swing', name: 'Arp Swing', section: 'Arp', offset: 163, kind: 'value', description: 'Arpeggiator swing amount' },
  { id: 'arp-octave', name: 'Arp Octaves', section: 'Arp', offset: 164, kind: 'enum', enumMax: 3, options: ARP_OCTAVES, description: 'Arpeggiator octave range' },
  // FX
  { id: 'fx-routing', name: 'FX Routing', section: 'FX', offset: 165, kind: 'enum', enumMax: 9, options: FX_ROUTINGS, description: 'Effects routing mode' },
  { id: 'fx1-type', name: 'FX1 Type', section: 'FX1', offset: 166, kind: 'enum', enumMax: 49, options: FX_TYPES, description: 'Effects slot 1 type' },
  ...Array.from({ length: 12 }, (_, i) => ({
    id: `fx1-param${i + 1}`, name: `FX1 Param ${i + 1}`, section: 'FX1', offset: 167 + i, kind: 'value', description: `Effects slot 1 parameter ${i + 1}`
  })),
  { id: 'fx2-type', name: 'FX2 Type', section: 'FX2', offset: 179, kind: 'enum', enumMax: 49, options: FX_TYPES, description: 'Effects slot 2 type' },
  ...Array.from({ length: 12 }, (_, i) => ({
    id: `fx2-param${i + 1}`, name: `FX2 Param ${i + 1}`, section: 'FX2', offset: 180 + i, kind: 'value', description: `Effects slot 2 parameter ${i + 1}`
  })),
  { id: 'fx3-type', name: 'FX3 Type', section: 'FX3', offset: 192, kind: 'enum', enumMax: 49, options: FX_TYPES, description: 'Effects slot 3 type' },
  ...Array.from({ length: 12 }, (_, i) => ({
    id: `fx3-param${i + 1}`, name: `FX3 Param ${i + 1}`, section: 'FX3', offset: 193 + i, kind: 'value', description: `Effects slot 3 parameter ${i + 1}`
  })),
  { id: 'fx4-type', name: 'FX4 Type', section: 'FX4', offset: 205, kind: 'enum', enumMax: 49, options: FX_TYPES, description: 'Effects slot 4 type' },
  ...Array.from({ length: 12 }, (_, i) => ({
    id: `fx4-param${i + 1}`, name: `FX4 Param ${i + 1}`, section: 'FX4', offset: 206 + i, kind: 'value', description: `Effects slot 4 parameter ${i + 1}`
  })),
  { id: 'fx1-gain', name: 'FX1 Output Gain', section: 'FX1', offset: 218, kind: 'value', description: 'Effects slot 1 output gain' },
  { id: 'fx2-gain', name: 'FX2 Output Gain', section: 'FX2', offset: 219, kind: 'value', description: 'Effects slot 2 output gain' },
  { id: 'fx3-gain', name: 'FX3 Output Gain', section: 'FX3', offset: 220, kind: 'value', description: 'Effects slot 3 output gain' },
  { id: 'fx4-gain', name: 'FX4 Output Gain', section: 'FX4', offset: 221, kind: 'value', description: 'Effects slot 4 output gain' },
  { id: 'fx-mode', name: 'FX Mode', section: 'FX', offset: 222, kind: 'enum', enumMax: 2, options: FX_MODES, description: 'Effects engine mode' },
  // Patch name (bytes 223-238)
  { id: 'patch-name', name: 'Patch Name', section: 'Name', offset: 223, length: 16, kind: 'name', description: 'Patch display name (16 chars)' },
  // Extended / firmware v2+ (bytes 245-247)
  // Unmapped bytes 239-244, 248-241
  { id: 'byte-239', name: 'Byte 239', section: 'Reserved', offset: 239, kind: 'value', description: 'Reserved byte' },
  { id: 'byte-240', name: 'Byte 240', section: 'Reserved', offset: 240, kind: 'value', description: 'Reserved byte' },
  { id: 'byte-241', name: 'Byte 241', section: 'Reserved', offset: 241, kind: 'value', description: 'Reserved byte' },
  // Extended / firmware v2+ (bytes 245-247)
  { id: 'vcf-model', name: 'VCF Model', section: 'VCF', offset: 245, kind: 'enum', enumMax: 2, options: VCF_MODELS, description: 'VCF filter model (firmware v2+)' },
  { id: 'vcf-moog-submode', name: 'Moog Filter Type', section: 'VCF', offset: 246, kind: 'enum', enumMax: 2, options: VCF_MOOG_TYPES, description: 'Moog filter sub-type (firmware v2+)' },
  { id: 'vcf-korg-submode', name: 'Korg Filter Type', section: 'VCF', offset: 247, kind: 'enum', enumMax: 1, options: VCF_KORG_TYPES, description: 'Korg filter sub-type (firmware v2+)' }
];

/**
 * Decode a single DeepMind 12 parameter from raw patch data.
 * Replicates ABDEep's PatchByteCodec::rawToNormalized logic.
 */
export function decodeDeepMindParameter(parameter, rawData) {
  const offset = parameter.offset;
  if (parameter.kind === 'name') {
    const len = parameter.length || 16;
    if (offset + len > rawData.length) return null;
    const raw = new TextDecoder().decode(rawData.slice(offset, offset + len));
    const nulIdx = raw.indexOf('\0');
    const str = nulIdx >= 0 ? raw.slice(0, nulIdx) : raw;
    return str.replace(/[^\x20-\x7e]/g, '').trim();
  }
  if (offset >= rawData.length) return null;
  const raw = rawData[offset];
  if (parameter.kind === 'bipolar') {
    // ((raw - 128) / 127 + 1) / 2, clamped 0..1
    const v = ((raw - 128) / 127 + 1) / 2;
    return Math.max(0, Math.min(1, v));
  }
  if (parameter.kind === 'enum') {
    if (parameter.enumMax > 0) return Math.min(1, raw / parameter.enumMax);
    return raw / 255;
  }
  // value: raw / 255
  return raw / 255;
}

/**
 * Decode all DeepMind 12 parameters from a 242-byte raw patch.
 * Returns an array of parameter objects with decoded values and display info.
 */
export function decodeDeepMindParameters(rawData) {
  return DEEPMIND_PARAMETER_SCHEMA.map(parameter => {
    const value = decodeDeepMindParameter(parameter, rawData);
    let displayValue = '';

    if (parameter.kind === 'name') {
      displayValue = value || '';
    } else if (parameter.kind === 'enum' && parameter.options && value !== null) {
      const index = Math.round(value * (parameter.enumMax || 1));
      displayValue = parameter.options[index] || `#${index}`;
    } else if (value !== null) {
      displayValue = typeof value === 'number' ? (value * 100).toFixed(1) + '%' : String(value);
    }

    return {
      ...parameter,
      value,
      displayValue,
      rawByte: parameter.kind !== 'name' && parameter.offset < rawData.length ? rawData[parameter.offset] : null
    };
  });
}

/**
 * Get parameters grouped by section for organized display.
 */
export function getDeepMindParametersBySection(rawData) {
  const params = decodeDeepMindParameters(rawData);
  const sections = {};
  for (const param of params) {
    const section = param.section || 'Other';
    if (!sections[section]) sections[section] = [];
    sections[section].push(param);
  }
  return sections;
}

/**
 * Get the raw byte map name for a given offset (for fallback display).
 */
export function getByteMapName(offset) {
  return offset < RAW_BYTE_MAP.length ? RAW_BYTE_MAP[offset] : `Byte ${offset}`;
}
