/**
 * MF.6 — Hardware Specification Sheets
 *
 * Pre-populated data for each supported hardware model.
 * User-editable notes are stored separately in the bank object.
 */

const SPECS = {
  'yamaha-dx7': {
    manufacturer: 'Yamaha',
    model: 'DX7',
    year: 1983,
    type: 'FM Digital',
    synthesis: '6-operators FM (Frequency Modulation)',
    polyphony: 16,
    voices: 32,
    oscillators: '6-operator FM × 32 algorithms',
    keyboard: '61 keys (aftertouch)',
    display: 'LCD 24×2 characters',
    midi: 'In / Out / Thru',
    audio: '2× mono out (L/R)',
    connections: ['MIDI In/Out/Thru', 'Phones', 'Foot控制器', 'Audio Out L/R'],
    effects: 'None (external)',
    arpeggiator: 'No',
    sequencer: 'No',
    modMatrix: '32 algorithms, feedback routing',
    dimensions: '1007 × 295 × 110 mm',
    weight: '14.5 kg',
    power: 'Internal PSU',
    firmware: null,
    links: {
      manual: 'https://usa.yamaha.com/products/contents/archive_en/synthesizers/dx7/dx7_om.html',
      website: 'https://usa.yamaha.com/products/musical_instruments/synthesizers/dx/dx7/index.html',
    },
    notes: 'First commercially successful digital synthesizer. Defined the sound of the 80s.',
  },

  'yamaha-dx7ii': {
    manufacturer: 'Yamaha',
    model: 'DX7 II / DX7 IIFD / DX7s',
    year: 1987,
    type: 'FM Digital',
    synthesis: '6-operators FM with improved features',
    polyphony: 16,
    voices: 64,
    oscillators: '6-operator FM × 32 algorithms',
    keyboard: '61 keys (aftertouch, velocity)',
    display: 'LCD graphic',
    midi: 'In / Out / Thru',
    audio: '2× stereo out',
    connections: ['MIDI In/Out/Thru', 'Phones', 'Foot控制器', 'Audio Out L/R', 'FD Drive (IIFD)'],
    effects: 'None (external)',
    arpeggiator: 'No',
    sequencer: 'No',
    modMatrix: '32 algorithms, velocity sensitivity',
    dimensions: '1007 × 295 × 110 mm',
    weight: '14.5 kg',
    power: 'Internal PSU',
    firmware: null,
    links: {
      manual: 'https://usa.yamaha.com/products/contents/archive_en/synthesizers/dx7ii/dx7ii_om.html',
    },
    notes: 'Improved DX7 with velocity sensitivity, more patches, and optional floppy drive.',
  },

  'behringer-pro800': {
    manufacturer: 'Behringer',
    model: 'Pro-800',
    year: 2022,
    type: 'Analog Polyphonic',
    synthesis: 'Dual VCO per voice, analog',
    polyphony: 8,
    voices: '400 (100 per bank × 4 banks)',
    oscillators: '2 VCO per voice (saw, square, triangle, noise)',
    keyboard: 'None (desktop module)',
    display: 'OLED',
    midi: 'In / Out',
    audio: '2× 6.3mm mono out',
    connections: ['MIDI In/Out', 'Audio Out L/R', 'Headphones', 'CV/Gate'],
    effects: 'None (external)',
    arpeggiator: 'Yes',
    sequencer: 'No',
    modMatrix: 'Mod matrix with multiple sources/destinations',
    dimensions: '200 × 130 × 50 mm',
    weight: '0.8 kg',
    power: 'USB-C or external PSU',
    firmware: 'v1.4.4+',
    links: {
      manual: 'https://www.behringer.com/product.html?modelCode=0602-AAH',
      website: 'https://www.behringer.com/product.html?modelCode=0602-AAH',
    },
    notes: 'Digital clone of Sequential Circuits Pro-One. 8-voice polyphonic analog synth.',
  },

  'behringer-deepmind12': {
    manufacturer: 'Behringer',
    model: 'DeepMind 12',
    year: 2016,
    type: 'Analog Polyphonic',
    synthesis: 'DCO analog with digital effects',
    polyphony: 12,
    voices: '1024 (128 per bank × 8 banks)',
    oscillators: '2 DCO per voice',
    keyboard: '61 keys (aftertouch, velocity)',
    display: 'TFT color LCD',
    midi: 'In / Out / Thru',
    audio: '2× 6.3mm stereo out',
    connections: ['MIDI In/Out/Thru', 'Audio Out L/R', 'Headphones', 'USB', 'Pedal', 'Ext. Audio In'],
    effects: '6 engines: Chorus, Flanger, Phaser, Delay, Reverb, Rotary',
    arpeggiator: 'Yes',
    sequencer: 'Yes (16-track)',
    modMatrix: '3 sources × 8 destinations',
    dimensions: '945 × 315 × 105 mm',
    weight: '11.5 kg',
    power: 'Internal PSU',
    firmware: 'v2.0.7+',
    links: {
      manual: 'https://www.behringer.com/product.html?modelCode=0602-AAF',
      website: 'https://www.behringer.com/product.html?modelCode=0602-AAF',
    },
    notes: '12-voice analog polysynth with extensive modulation and built-in effects.',
  },

  'casio-cz101': {
    manufacturer: 'Casio',
    model: 'CZ-101',
    year: 1984,
    type: 'Phase Distortion Digital',
    synthesis: 'Phase Distortion (PD synthesis)',
    polyphony: 8,
    voices: '16 (per bank)',
    oscillators: '2 oscillators per voice (8 waveforms)',
    keyboard: '49 mini-keys',
    display: 'LED numeric',
    midi: 'In / Out',
    audio: '2× 3.5mm mono out',
    connections: ['MIDI In/Out', 'Audio Out L/R', 'Phones', 'DC input'],
    effects: 'None (external)',
    arpeggiator: 'No',
    sequencer: 'No',
    modMatrix: 'Vibrato, tremolo, attack',
    dimensions: '583 × 212 × 62 mm',
    weight: '2.3 kg',
    power: '6× AA batteries or adapter',
    firmware: null,
    links: {
      manual: 'https://www.casio.com/intl/archive/support/owner-manuals/',
    },
    notes: 'Compact digital synth using Phase Distortion synthesis. Battery powered.',
  },

  'casio-cz1000': {
    manufacturer: 'Casio',
    model: 'CZ-1000',
    year: 1985,
    type: 'Phase Distortion Digital',
    synthesis: 'Phase Distortion (PD synthesis)',
    polyphony: 8,
    voices: 16,
    oscillators: '2 oscillators per voice',
    keyboard: '49 full-size keys',
    display: 'LED numeric',
    midi: 'In / Out',
    audio: '2× 6.3mm mono out',
    connections: ['MIDI In/Out', 'Audio Out L/R', 'Phones'],
    effects: 'None',
    arpeggiator: 'No',
    sequencer: 'No',
    modMatrix: 'Vibrato, tremolo, attack',
    dimensions: '815 × 260 × 85 mm',
    weight: '5.5 kg',
    power: 'External PSU',
    firmware: null,
    links: {},
    notes: 'Full-size keyboard version of the CZ-101.',
  },

  'casio-cz5000': {
    manufacturer: 'Casio',
    model: 'CZ-5000',
    year: 1985,
    type: 'Phase Distortion Digital',
    synthesis: 'Phase Distortion (PD synthesis)',
    polyphony: 8,
    voices: '32 (2 banks of 16)',
    oscillators: '2 oscillators per voice',
    keyboard: '61 full-size keys',
    display: 'LED numeric',
    midi: 'In / Out',
    audio: '2× 6.3mm mono out',
    connections: ['MIDI In/Out', 'Audio Out L/R', 'Phones', 'Ext. Audio In'],
    effects: 'None',
    arpeggiator: 'No',
    sequencer: 'Yes (built-in sequencer)',
    modMatrix: 'Vibrato, tremolo, attack',
    dimensions: '1005 × 300 × 100 mm',
    weight: '8.5 kg',
    power: 'External PSU',
    firmware: null,
    links: {},
    notes: 'Larger CZ with built-in sequencer. Double the patches of CZ-101.',
  },

  'casio-cz1': {
    manufacturer: 'Casio',
    model: 'CZ-1',
    year: 1986,
    type: 'Phase Distortion Digital',
    synthesis: 'Phase Distortion (PD synthesis)',
    polyphony: 8,
    voices: '64 (4 banks of 16)',
    oscillators: '2 oscillators per voice',
    keyboard: '61 keys (velocity sensitive)',
    display: 'LCD',
    midi: 'In / Out / Thru',
    audio: '2× 6.3mm stereo out',
    connections: ['MIDI In/Out/Thru', 'Audio Out L/R', 'Phones', 'Ext. Audio In', 'Foot pedal'],
    effects: 'None',
    arpeggiator: 'No',
    sequencer: 'No',
    modMatrix: 'Velocity-sensitive PD synthesis',
    dimensions: '1050 × 320 × 110 mm',
    weight: '10 kg',
    power: 'External PSU',
    firmware: null,
    links: {},
    notes: 'Top-of-line CZ with velocity sensitivity and 4 banks.',
  },

  'roland-juno106': {
    manufacturer: 'Roland',
    model: 'Juno-106',
    year: 1984,
    type: 'Analog Polyphonic',
    synthesis: 'DCO analog with chorus',
    polyphony: 6,
    voices: '128 (64 per bank × 2 banks)',
    oscillators: '1 DCO per voice (pulse, saw, noise, sub)',
    keyboard: '61 keys (aftertouch)',
    display: 'LED numeric',
    midi: 'In / Out',
    audio: '2× 6.3mm mono out',
    connections: ['MIDI In/Out', 'Audio Out L/R', 'Phones', 'Ext. Audio In', 'Chord Hold', 'Pedal'],
    effects: 'Built-in Chorus (I/II)',
    arpeggiator: 'No',
    sequencer: 'No',
    modMatrix: 'LFO to VCF/VCO, bender',
    dimensions: '990 × 290 × 100 mm',
    weight: '11 kg',
    power: 'Internal PSU',
    firmware: null,
    links: {
      manual: 'https://archive.org/details/roland-juno-106-owners-manual',
    },
    notes: 'Classic analog polysynth. Known for warm chorus and easy programming. MIDI was added after initial release.',
  },

  'roland-juno60': {
    manufacturer: 'Roland',
    model: 'Juno-60',
    year: 1982,
    type: 'Analog Polyphonic',
    synthesis: 'DCO analog with chorus',
    polyphony: 6,
    voices: 56,
    oscillators: '1 DCO per voice',
    keyboard: '61 keys',
    display: 'LED numeric',
    midi: 'None (original)',
    audio: '2× 6.3mm mono out',
    connections: ['Audio Out L/R', 'Phones', 'Ext. Audio In', 'Arpeggiator In', 'Chord Hold'],
    effects: 'Built-in Chorus (I/II)',
    arpeggiator: 'Yes (built-in)',
    sequencer: 'No',
    modMatrix: 'LFO to VCF/VCO, bender',
    dimensions: '990 × 290 × 100 mm',
    weight: '11 kg',
    power: 'Internal PSU',
    firmware: null,
    links: {},
    notes: 'Pre-MIDI Juno with built-in arpeggiator. Iconic analog pad sound.',
  },

  'roland-juno6': {
    manufacturer: 'Roland',
    model: 'Juno-6',
    year: 1982,
    type: 'Analog Polyphonic',
    synthesis: 'DCO analog with chorus',
    polyphony: 6,
    voices: 56,
    oscillators: '1 DCO per voice',
    keyboard: '61 keys',
    display: 'LED numeric',
    midi: 'None',
    audio: '2× 6.3mm mono out',
    connections: ['Audio Out L/R', 'Phones', 'Ext. Audio In'],
    effects: 'Built-in Chorus',
    arpeggiator: 'Yes',
    sequencer: 'No',
    modMatrix: 'LFO to VCF/VCO',
    dimensions: '990 × 290 × 100 mm',
    weight: '11 kg',
    power: 'Internal PSU',
    firmware: null,
    links: {},
    notes: 'First in the Juno series. Similar to Juno-60 but without some features.',
  },

  'roland-hs60': {
    manufacturer: 'Roland',
    model: 'HS-60',
    year: 1984,
    type: 'Analog Polyphonic',
    synthesis: 'DCO analog with chorus',
    polyphony: 6,
    voices: 64,
    oscillators: '1 DCO per voice',
    keyboard: '61 keys',
    display: 'LED numeric',
    midi: 'In / Out',
    audio: '2× 6.3mm mono out',
    connections: ['MIDI In/Out', 'Audio Out L/R', 'Phones'],
    effects: 'Built-in Chorus',
    arpeggiator: 'No',
    sequencer: 'No',
    modMatrix: 'LFO to VCF/VCO',
    dimensions: '990 × 290 × 100 mm',
    weight: '11 kg',
    power: 'Internal PSU',
    firmware: null,
    links: {},
    notes: 'MIDI-equipped version of the Juno-60 platform. Sold in some markets as HS-60.',
  },

  'korg-ms2000': {
    manufacturer: 'Korg',
    model: 'MS2000',
    year: 2000,
    type: 'Virtual Analog',
    synthesis: 'Modeling analog synthesis',
    polyphony: 4,
    voices: '128 (16 per bank × 8 banks)',
    oscillators: '2 oscillators per voice (multiple waveforms)',
    keyboard: '44 keys (velocity)',
    display: 'LCD with knobs per parameter',
    midi: 'In / Out',
    audio: '2× 6.3mm mono out',
    connections: ['MIDI In/Out', 'Audio Out L/R', 'Headphones', 'Ext. Audio In', 'Pedal'],
    effects: 'Modulation effects, delay',
    arpeggiator: 'Yes',
    sequencer: 'No',
    modMatrix: 'Virtual analog with real-time knobs',
    dimensions: '744 × 260 × 72 mm',
    weight: '4.5 kg',
    power: 'External PSU',
    firmware: null,
    links: {
      manual: 'https://www.korg.com/us/support/download/manual/0/131/1746/',
    },
    notes: 'Virtual analog synth with knob-per-function interface. Shares SysEx format with microKORG.',
  },

  'korg-microkorg': {
    manufacturer: 'Korg',
    model: 'microKORG',
    year: 2002,
    type: 'Virtual Analog + Vocoder',
    synthesis: 'Modeling analog synthesis + vocoder',
    polyphony: 4,
    voices: '128 (16 per bank × 8 banks)',
    oscillators: '2 oscillators per voice',
    keyboard: '37 mini-keys (velocity)',
    display: 'LCD',
    midi: 'In / Out',
    audio: '2× 6.3mm mono out',
    connections: ['MIDI In/Out', 'Audio Out L/R', 'Headphones', 'Mic In (vocoder)'],
    effects: 'Modulation, delay, vocoder',
    arpeggiator: 'Yes',
    sequencer: 'No',
    modMatrix: 'Virtual analog with matrix modulation',
    dimensions: '515 × 208 × 65 mm',
    weight: '2.5 kg',
    power: 'External PSU (included)',
    firmware: null,
    links: {
      manual: 'https://www.korg.com/us/support/download/manual/0/131/1745/',
    },
    notes: 'Best-selling virtual analog synth. Shares SysEx format with MS2000. Includes vocoder with mic input.',
  },

  'korg-prophecy': {
    manufacturer: 'Korg',
    model: 'Prophecy',
    year: 1995,
    type: 'Physical Modeling + VA',
    synthesis: 'Physical Modeling, VA, Sample-based',
    polyphony: 1,
    voices: 128,
    oscillators: 'Multiple modeling engines (Bass, Reed, Brass, Guitar, etc.)',
    keyboard: '44 keys (polyphonic aftertouch, ribbon controller)',
    display: 'LED',
    midi: 'In / Out',
    audio: '2× 6.3mm mono out',
    connections: ['MIDI In/Out', 'Audio Out L/R', 'Headphones', 'Expression pedal'],
    effects: 'Built-in effects per engine',
    arpeggiator: 'No',
    sequencer: 'No',
    modMatrix: 'Ribbon controller, mod wheel, aftertouch',
    dimensions: '780 × 260 × 70 mm',
    weight: '4.5 kg',
    power: 'External PSU',
    firmware: null,
    links: {},
    notes: 'Monophonic physical modeling synth with ribbon controller. Unique sound design tool.',
  },
};

/**
 * Get hardware spec for a model.
 * @param {string} modelId
 * @returns {object|null}
 */
export function getHardwareSpec(modelId) {
  return SPECS[modelId] || null;
}

/**
 * Get all available spec keys.
 * @returns {string[]}
 */
export function getAvailableSpecModels() {
  return Object.keys(SPECS);
}

export default SPECS;
